### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by virgo77** [Rabbit-Company/Passky-Server#20]
**Describe the bug**
Trying to update to v8.0.0 and I get an error:
```
#> sudo docker-compose pull
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```

**To Reproduce**
Just connected as root (or user with sudo rights)

**Desktop (please complete the following information):**
 - OS: Debian 11.5 (up to date)
 - Docker: 20.10.5+dfsg1, build 55c4c88
 - Docker-Compose: 1.25.0, build unknown <-- normal?

**Additional context**
Passky server is on http instead https. I don't know how to switch to https.
Is this the origin issue?

**Comment by zigazajc007** [comment]
> Passky server is on http instead https. I don't know how to switch to https.
> Is this the origin issue?

This is correct Passky will by default assign on port 8080. Normally users host multiple applications on the same server, that's why we use a proxy manager. One of the easiest proxy manager to use is [Nginx Proxy Manager](https://nginxproxymanager.com/guide/#quick-setup).

How to install Nginx Proxy Manager:
1. Create new directory and navigate to it (`mkdir nginx && cd nginx`)
2. Create new file called docker-compose.yml (`nano docker-compose.yml`)
3. Past this configuration: 
```yml
version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```
4. Now you can start the Nginx Proxy Manager with `sudo docker-compose up -d`
5. To access admin panel go to your browser and use http://IPOfYourServer:81
6. Enter default username and password:
```yml
Email: admin@example.com
Password: changeme
```
7. Now you can create new proxy with your domain that will redirect traffic to port 8080 and also auto install SSL certificate.

Note that I would use proxy manager for Passky only if you will open access to the public. For home use only you do not need it.

I can make a video on how to install Passky, so it would be a lot easier for beginners.
